version: "3"

services:
  nginx-server:
    build:
      context: ./nginx
    restart: always
    ports:
      - "8080:80"
    networks:
      - nodenet

  db:
    platform: linux/x86_64
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - nodenet

  app:
    build:
      context: ./node
      dockerfile: dockerfile
    networks:
      - nodenet
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    container_name: app
    tty: true
    entrypoint: wait-for db:3306 -t 40 -- npm start
    depends_on:
      - db

networks:
  nodenet:
    driver: bridge
